import React from 'react'
import { Badge } from './Badge'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  'https://www.figma.com/design/0OB1JVXSqaxmJDrP7qAMJr?node-id=9892%3A4941',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum('variant', {
        info: 'info',
        warning: 'warning',
      }),
      size: figma.enum('size', {
        small: 'sm',
      }),
      value: figma.string('value'),
    },
    example: props => (
      <Badge variant={props.variant} size={props.size} value={props.value} />
    ),
  }
)
