import React from 'react'
import { Button } from './Button'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  'https://www.figma.com/design/0OB1JVXSqaxmJDrP7qAMJr?node-id=577%3A12160',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum('variant', {
        primary: 'primary',
        glass: 'glass',
      }),
      shape: figma.enum('shape', {
        circle: 'circle',
        square: 'square',
      }),
      disabled: figma.enum('state', {
        disabled: true,
      }),
      size: figma.enum('size', {
        small: 'sm',
        xsmall: 'xs',
      }),
      label: figma.string('label'),
      leftIcon: figma.instance('leftIcon'),
      // hasLeftIcon: figma.boolean("hasLeftIcon"),
      // hasRightIcon: figma.boolean("hasRightIcon")
      // No matching props could be found for these Figma properties:
      // rightIcon: figma.instance('rightIcon'),
      // "hasRightIcon": figma.boolean('hasRightIcon'),
      // "hasLeftIcon": figma.boolean('hasLeftIcon')
    },
    example: props => (
      <Button
        variant={props.variant}
        shape={props.shape}
        disabled={props.disabled}
        size={props.size}
        label={props.label}
        leftIcon={props.leftIcon}
      />
    ),
  }
)
