import React from "react"
import { Toast } from "./Toast"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Toast,
  "https://www.figma.com/design/0OB1JVXSqaxmJDrP7qAMJr?node-id=9895%3A7000",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      description: figma.string("description"),
      variant: figma.enum("variant", {
        success: "success",
        error: "error",
      }),
      // No matching props could be found for these Figma properties:
      // "showDescription": figma.boolean('Show Description'),
      // "showIcon": figma.boolean('Show Icon'),
      // "title": figma.string('title'),
      // "description": figma.string('description')
    },
    example: (props) => (
      <Toast description={props.description} variant={props.variant} />
    ),
  },
)
