import figma from '@figma/code-connect'
import React from 'react'

import { Divider } from './Divider'

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Divider,
  'https://www.figma.com/design/0OB1JVXSqaxmJDrP7qAMJr?node-id=11869-30796',
  {
    example: () => <Divider />,
  }
)
