import figma from '@figma/code-connect'
import React from 'react'

import { ContextMenuIcon } from '../../icons'
import { IconButton } from '../IconButton'

import {
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuRoot,
  DropdownMenuTrigger,
} from './DropdownMenu'

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  DropdownMenuRoot,
  'https://www.figma.com/design/0OB1JVXSqaxmJDrP7qAMJr?node-id=11510%3A28005',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "showButton": figma.boolean('Show button'),
      // "ponting": figma.enum('ponting', {
      //   "default": "default",
      //   "inverted": "inverted"
      // })
    },
    example: props => (
      <DropdownMenuRoot>
        <DropdownMenuRoot>
          <DropdownMenuTrigger asChild>
            <IconButton icon={ContextMenuIcon} />
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem>Item 1</DropdownMenuItem>
            <DropdownMenuItem>Item 2</DropdownMenuItem>
            <DropdownMenuItem>Item 3</DropdownMenuItem>
            <DropdownMenuItem>Item 4</DropdownMenuItem>
            <DropdownMenuItem>Item 5</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenuRoot>
      </DropdownMenuRoot>
    ),
  }
)
