import React from "react"
import { Breadcrumbs } from "./Breadcrumbs"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Breadcrumbs,
  "https://www.figma.com/design/0OB1JVXSqaxmJDrP7qAMJr?node-id=11294%3A72770",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "current": figma.string('Current'),
      // "showWallet": figma.boolean('show wallet'),
      // "showBack": figma.boolean('show back'),
      // "showInfo": figma.boolean('show info'),
      // "level": figma.enum('Level', {
      //   "5": "5",
      //   "4": "4",
      //   "3": "3",
      //   "2": "2"
      // })
    },
    example: (props) => <Breadcrumbs paths={/* TODO */} />,
  },
)
