import React from "react"
import { Tooltip } from "./Tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/0OB1JVXSqaxmJDrP7qAMJr?node-id=10757%3A3364",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "label2": figma.string('label 2'),
      // "label1": figma.string('label 1'),
      // "orientation": figma.enum('orientation', {
      //   "down": "down",
      //   "up": "up",
      //   "left": "left",
      //   "right": "right",
      //   "orientation8": "orientation8",
      //   "orientation7": "orientation7",
      //   "orientation6": "orientation6",
      //   "orientation5": "orientation5"
      // }),
      // "icon": figma.boolean('icon')
    },
    example: (props) => <Tooltip message={/* TODO */} />,
  },
)
